import type { Metadata } from "next";
import "../globals.css";
import Theme from "@/context/ThemeContext";
import { ABeeZee } from "next/font/google";

const abeezee = ABeeZee({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Sentiments Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${abeezee.className} dark:bg-background text-primary w-screen h-screen overflow-hidden`}
        suppressHydrationWarning
      >
        <Theme>
          <main className="h-full w-full overflow-x-hidden">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
