name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  install-backend:
    name: Install Backend Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies in backend
        run: |
          cd backend
          npm install

  install-frontend:
    name: Install Frontend Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies in frontend
        run: |
          cd frontend
          npm install

  install-mobile:
    name: Install Mobile Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js for Mobile
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies in mobile
        run: |
          cd mobile
          npm install

  sonarcloud:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [install-backend, install-frontend, install-mobile]
    steps:
      - uses: actions/checkout@v3
      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=244Walyson_recipes \
            -Dsonar.organization=244Walyson \
            -Dsonar.sources=backend/src,frontend/src,mobile/src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
