name: SonarCloud

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: "Token for SonarCloud"
        required: true

  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js modules for backend
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node

      - name: Cache Node.js modules for frontend
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node

      - name: Cache Node.js modules for mobile
        uses: actions/cache@v3
        with:
          path: mobile/node_modules
          key: ${{ runner.os }}-mobile-node-${{ hashFiles('mobile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-mobile-node

      - name: Install dependencies in backend
        run: |
          cd backend
          npm install

      - name: Install dependencies in frontend
        run: |
          cd frontend
          npm install

      - name: Install dependencies in mobile
        run: |
          cd mobile
          npm install

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=244walyson_GWApp \
            -Dsonar.organization=seu_organizacao_no_sonarcloud \
            -Dsonar.sources=backend/src,frontend/src,mobile/src \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
